# -*- coding: utf-8 -*-
"""task-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBbOqknRu4ftThvcMV1DpAlpq7w4AtL9
"""

from matplotlib import pyplot as plt
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array

img_path='/content/hunu.jpg'
img = load_img(img_path)

img_array =img_to_array(img)

img_array =img_array.reshape((1,) + img_array.shape)

img