# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYf61dc7UcPljvrYSLddbd_4Txc9zn13
"""

!pip install transformers

from transformers import pipeline

translater = pipeline("translation_en_to_fr")

text = input('enter the text to translate: ')

res = translater(text)

res